package:
  name: palettable
  version: "2.1.1"

source:
  fn: palettable-2.1.1.tar.gz
  url: https://files.pythonhosted.org/packages/e3/68/c62400c0d82df46b6b3e3eb860de66a676b91284ed651b78321b34c19ed6/palettable-2.1.1.tar.gz
  md5: 60adcbda83e1eaa331c5fdc5dfbcc4ff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - palettable = palettable:main
    #
    # Would create an entry point called palettable that calls palettable.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - palettable
    - palettable.colorbrewer
    - palettable.cubehelix
    - palettable.tableau
    - palettable.wesanderson

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://jiffyclub.github.io/palettable/
  license: MIT License
  summary: 'Color palettes for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
