package:
  name: codetransformer
  version: "0.6.0"

source:
  fn: codetransformer-0.6.0.tar.gz
  url: https://pypi.python.org/packages/ed/35/d036925009d467d81b43b8ff36a6d128ff1b0f6ce27836c0bba0f03d5c49/codetransformer-0.6.0.tar.gz
  md5: 5e422c681e1ac6abfe20444971a029ff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - codetransformer = codetransformer:main
    #
    # Would create an entry point called codetransformer that calls codetransformer.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - toolz

  run:
    - python
    - toolz

test:
  # Python imports
  imports:
    - codetransformer
    - codetransformer.decompiler
    - codetransformer.tests
    - codetransformer.transformers
    - codetransformer.transformers.tests
    - codetransformer.utils
    - codetransformer.utils.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/llllllllll/codetransformer
  license: GNU General Public License v2 (GPLv2)
  summary: 'Python code object transformers'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
